### PR TITLE
Added disable header prop

### PR DESCRIPTION
**Pull request by mihaibogdan**
Added the option to disable the header and show only the rows.

### CODE REVIEW

**Review by pupudu — APPROVED** [review]
Good work mate. Thanks a lot for this contribution

**Comment by pupudu** [comment]
Published v0.13.0 🎉

**Comment by mihaibogdan** [comment]
Hi mate,

Hope you're doing well. I am using your project in production and I have a
small issue. I've updated to react 17 but I see that window-table requires
react 16.8 to work. Otherwise, I get this error:

While resolving: ***@***.***
npm ERR! Found: ***@***.***
npm ERR! node_modules/react
npm ERR!   peer react@">=16.8.0" from @***@***.***

Do you think we can update the peerDependencies property from package.json?

Thank you so much for your help!

**Comment by pupudu** [comment]
Hey mate. Yes I can do that for you. Will update here once done 🔥

**Comment by pupudu** [comment]
@mihaibogdan Updated and published v1.0.0 
Let me know if you find any issues with the release. Thanks for using window-table

**Comment by mihaibogdan** [comment]
Wow, so quick mate! Thank you very much, It works 🚀🚀

**Pull request merged**
